### ISSUE TITLE
Can't run login.py

### ISSUE THREAD

**Issue by CardanoNFTs** [TobiasPankner/Gleam-giveaway-bot#18]
I filled out the config file but every time I try to run the login.py script, it gives me this error:

Traceback (most recent call last):
  File ".\login.py", line 3, in <module>
    from src import browser
  File "C:\Users\User\Desktop\Gleam-giveaway-bot-master\src\browser.py", line 14
    driver: webdriver.Chrome = None
          ^

**Comment by TobiasPankner** [comment]
Please provide the full error message.  
If it was syntax Error you need to update python to 3.6 or later.

**Comment by red0-x** [comment]
I think he doesn't have chromedriver get chromedriver at https://chromedriver.chromium.org/
