### ISSUE TITLE
Message: invalid argument: user data directory is already in use

### ISSUE THREAD

**Issue by BoneJuice808** [TobiasPankner/Gleam-giveaway-bot#8]
**I receive the following error when trying to run login.py**

C:\Users\Spark\Gleam-giveaway>py login.py

[WDM] - Cache is valid for [25/12/2020]
[WDM] - Looking for [chromedriver 87.0.4280.88 win32] driver in cache
[WDM] - Driver found in cache [C:\Users\Spark\.wdm\drivers\chromedriver\87.0.4280.88\win32\chromedriver.exe]
Traceback (most recent call last):
  File "login.py", line 9, in <module>
    browser.init_driver(config['user-data-dir'], config['profile-directory'], headless=False)
  File "C:\Users\Spark\Gleam-giveaway\src\browser.py", line 95, in init_driver
    driver = webdriver.Chrome(ChromeDriverManager().install(), chrome_options=options, desired_capabilities=caps)
  File "C:\Python38\lib\site-packages\selenium\webdriver\chrome\webdriver.py", line 76, in __init__
    RemoteWebDriver.__init__(
  File "C:\Python38\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "C:\Python38\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "C:\Python38\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Python38\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.InvalidArgumentException: Message: invalid argument: user data directory is already in use, please specify a unique value for --user-data-dir argument, or don't use --user-data-dir

**Google Chrome opens but the gleam website does not show.**

Here is my config.json
![image](https://user-images.githubusercontent.com/76595751/103139896-20e48380-46af-11eb-8656-bf9cd809d3f8.png)

**Relatively new to python and thanks for the bot!**

**Comment by TobiasPankner** [comment]
Close all chrome windows and run it again
